#pragma once

template <class T>
class CProxy_IALEEvents : public IConnectionPointImpl<T, &__uuidof( _IALEEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
